[features]
seeds = false
skip-lint = false
[programs.localnet]
todo_sol = "DdBFCWyBbx5ip8ocecrCivEuzweRY6PKk8EbbANLHCGQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/thisbo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
